#include "parser.h"
#include "fonction-pwd.h"
#include "fonction-mkdir.h"
#include "fonction-cat.h"
#include "fonction-cd.h"
#include "fonction-ls.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <windows.h>
#include <sys/types.h>